#!/usr/bin/env ruby
require 'yaml'
require 'csv'
require 'io/console'

# mvc classes
require './classes/model.rb'
require './classes/view.rb'
require './classes/controller.rb'

@controller = ResgenController.new
@controller.run
